Small cosmetic changes.

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,10 +1,10 @@
 #!/bin/bash
 
+# Partially from http://lczero.org/dev/wiki/google-cloud-guide-lc0/
+
 TOP=$(cd ${0%/*}; pwd)
 
-echo $TOP
-
-# Partially from http://lczero.org/dev/wiki/google-cloud-guide-lc0/
+export PATH="$PATH:/usr/local/cuda/bin"
 
 install_cuda()
 {
@@ -67,8 +67,6 @@ install_engine()
 }
 
 
-export PATH="$PATH:/usr/local/cuda/bin"
-
 LIST=$*
 
 [ "$LIST" ] || LIST="cuda cudnn other lc0 weights engine"
@@ -82,6 +80,10 @@ do
     cd ~
 		install_$i
 		;;
+
+    *)
+    echo "Cannot install $i" >&2
+    ;;
 
 	esac
 
